### ISSUE TITLE
'join' used as method name in motif.py

### ISSUE THREAD

**Issue by j-andrews7** [j-andrews7/VAMPIRE#40]
`join` is a default method for iterables in python, it's almost certainly not a good idea to have a method named similarly. I can't find a case where it's actually used, but it should be removed or renamed as appropriate.

Offending method starts on line 79 of `motif.py`.

**Comment by Crumbs350** [comment]
Join was included as a good idea for future ability to process data.

join was defined as a class object method for MotifArray() class, not as a bare function. Don't believe it will cause an issue because join() is not a [base python function](https://docs.python.org/3.6/library/functions.html). join() on iterators is defined for each of those individual class object types and called as object.join() just like MotifArrayObject.join() would be called. I tested by importing motif class code and verifying normal iterator joins on strings still work:
```
import motif
a = "Hello, "
b = "world"
"-".join([a,b])
```
Prints: _'Hello, -world'_ as expected.

Still concerned?

**Comment by j-andrews7** [comment]
I guess not concerned if it doesn't cause a conflict, but feels like it may
cause some unnecessary confusion if a dev wanted to use the motifs/motif
module in their own code. Probably fine.
